### ISSUE TITLE
hide-text() does not hide text in conjunction with padding on Firefox

### ISSUE THREAD

**Issue by preist** [thoughtbot/bourbon#1014]
### Expected behavior
On all the browsers if you create an element with padding and apply the `hide-text()` mixin, it hides the text. I would expect this to work the same in Firefox, but it's not so. When you add `padding` to an element, it reveals the text on the right where the padding is. (see screenshot).

### Screenshots (if relevant)
![screenshot](https://cloud.githubusercontent.com/assets/14940633/24035798/a95f15da-0aff-11e7-8476-b47c7c5ff524.png)

### Suggested Fix
Instead of `text-indent: 101%` consider doing a `text-indent: 9999px`. This should make it behave the same on all the browsers. Except when 10K monitors become commonplace, it will occasionally stick out one pixel.

Or. An even better fix would be to write a small note in the documentation that says: If you use `padding` on Firefox you should set your own `text-indent` value.

#### `index.html`
```HTML
<!DOCTYPE html>
<html class="no-js">

  <head>
      <title>Pages</title>
      <link rel="stylesheet" href="styles.css">
  </head>

  <body>
    <!-- Image Replacement -->
    <h1 id="logo"><a href="http://thoughtbot.com">Thoughtbot Logo</a></h1>
  </body>

</html>
```

#### `styles.scss`
```SASS
@import "bourbon/bourbon";

#logo {
	text-align: center;

	a {
		display: block;
		height: 35px;
		width: 146px;
		margin: 0 auto;

		// Adding some padding
		padding: 40px;

		// Applying the mixin
		@include hide-text();

		background-image: url("thoughtbot.svg");
		background-repeat: no-repeat;
		background-position: center center;
		background-size: 146px 35px;
	}
}
```

### Bourbon version
Bourbon 5.0.0.beta.7

### Environment info
macOS Sierra Version 10.12.3
Firefox 51.0.1 (64-bit)

**Comment by tysongach** [comment]
Hi @preist!

We use [“the Kellum Method”](https://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/) for `hide-text`, which uses `text-indent: 101%` instead of`text-indent: 9999px` so to not draw a 9999px box offscreen which has performance implications.

I am able to re-create your issue in Firefox. I find it interesting that it is a Firefox-only issue (in my limited testing in other browsers). Since it is isolated, I’m hesitant to change how `hide-text` functions. I’d also recommend using `margin` instead of `padding` for your use-case, as `padding` technically is space _inside_ a box, so it sort of makes sense the text is visible.
