### ISSUE TITLE
Flow-Root support

### ISSUE THREAD

**Issue by rctneil** [thoughtbot/bourbon#1023]
Can `display: flow-root` be added to the clearfix utility?

Also, any new ETA on v5?

**Comment by tysongach** [comment]
What’s the purpose of adding that?

**Comment by rctneil** [comment]
Considering it's becoming implemented in more and more browsers and is a native clearfix function then I would say that using it is better over the clearfix included in Bourbon. If this was included then the browser could use that over the custom one?

Maybe my thinking is wrong.

**Comment by tysongach** [comment]
I believe `flow-root` will eventually deem the `clearfix` mixin pointless. So I don’t think we should set `display` to `flow-root` in the `clearfix` mixin, but rather document that this new property is gaining browser support, and that authors can begin using it as a native “clearfix” solution instead of the mixin.

**Comment by rctneil** [comment]
It's more in the meantime where browser support is not 100%. I know we can use:

```
display: flow-root;
@include clearfix;
```
But surely including it in the mixin by default would get it into use and as browser support increases we can remove use of the mixin and soley replace with the new display value on it's own.

**Comment by tysongach** [comment]
Yep, these are all good thoughts…couple more things to think about:

- The `clearfix` mixin already has a `display` set. 
- Does `flow-root` exactly mimic the same desired outcome that the `clearfix` mixin does? If they do accomplish the same thing, maybe they belong wrapped up together, but if they produce slightly different outcomes, should they be bundled?

**Comment by tysongach** [comment]
I’m going to close this as I don’t think there is any action here. Since the spec has not been formalized for `flow-root`, I’m hesitant to add it to the library. I also think `flow-root`—if it gains traction—will simply _replace_ our `clearfix` mixin all-together, meaning, you should just use `flow-root` if fits within your required browser support.
