### ISSUE TITLE
5.0 Status Check

### ISSUE THREAD

**Issue by bdkjones** [thoughtbot/bourbon#1027]
Hi team,

So...what is going on with 5.0? The latest release of that version is from November 2016 and there have been many updates to the 4.x track since then.

I've pinged you on Twitter a few times and you've told me that 5.0 is still alive and well but, frankly, that doesn't seem to be the case. Bourbon 5 is becoming the Duke Nukem Forever of the CSS world. 

Do you have a release date in mind? I moved my app to the Bourbon 5.x track a long time ago because I was told it was "coming soon". Should I roll back to 4.x? The Bourbon website has documentation for 4.x that doesn't apply to 5.x, so the huge delay and stalled progress make it tough for users.

Can we get some official clarity on the situation? Something more than, "it's still coming"? What's the real story?

**Comment by bdkjones** [comment]
The other thing that makes this a really confusing mess is that it *appears* that Bitters (as of 1.5.0) is dependent on Bourbon 5.0.0.beta7---a version of Bourbon that's not officially released:

<img width="822" alt="screen shot 2017-06-08 at 19 29 08" src="https://user-images.githubusercontent.com/926566/26958690-ece1d7da-4c80-11e7-9ce8-1d84c096ead7.png">

If I recall correctly, there's a similar situation for Neat. This is a large part of the reason I moved my app to the 5.0 release last fall when Bitters and Neat started depending on the 5.0 track, even though that release is technically still a beta.

But now I get a lot of email from users who are looking at the Bourbon.io website and (rightfully) asking me why such-and-such isn't working. I have to reply and explain that Bourbon is currently a bit messy, as it's moving from 4.x to 5.x and the website isn't up to date, but if they take a look at this GitHub post where the Bourbon team talks about migrating from 4->5, they'll be all set, etc.

So...maybe you guys can provide some clarity on what the heck is happening? I mean, even Apple finally fessed up about their Mac Pro fiasco, so I feel like if THEY can provide some honest communication, ThoughtBot can too!

**Comment by tysongach** [comment]
Hi @bdkjones!

Honestly, we’ve just been busy and other more important things have taken our time. Bourbon is alive, it’s stable and we use it everyday here at thoughtbot. But it is a free, open-source project that we spend our limited investment time on.

> Do you have a release date in mind?

No, we can’t commit to a date.

> it appears that Bitters (as of 1.5.0) is dependent on Bourbon 5.0.0.beta7

Yes, that's correct. We did that because we kick off nearly every new project with Bitters and so it was a great way to test drive Bourbon 5. In hindsight, I think this was a mistake and has led to confusion in the community.

> If I recall correctly, there's a similar situation for Neat.

Neat (as of 1.8) no longer depends on Bourbon. We’ve been doing work to de-couple pieces of the suite where it makes sense. Bitters remains dependent on Bourbon, but not Neat.

> This is a large part of the reason I moved my app to the 5.0 release last fall when Bitters and Neat started depending on the 5.0 track

Neat has never been dependent on 5.0, and as mentioned, is no longer dependent on Bourbon at all. One thing to note is that Bitters is a scaffold—a starting point—and not a library that should be imported. The files should be added straight to the project and edited to fits the project needs, throughout the lifetime of the project. I’m not sure how CodeKit works, but if it does import Bitters, we could be introducing an extra dependency tree that isn't necessary.

In the future, I think it’d be best to not package a beta release.

> But now I get a lot of email from users who are looking at the Bourbon.io website and (rightfully) asking me why such-and-such isn't working.

5.0 will add a versioned documentation site, which can help to prevent this in the future.

**Comment by pixelminds** [comment]
I had to stick with Bourbon 5 and Neat 1.8 because I wanted to use Refills. I would like to use Neat 2, not 1.8. It's nicer and more efficient, but will have to wait for the new version of Refills. I'm not going to ask for a date, just wanted to let you know.

**Comment by tysongach** [comment]
> but will have to wait for the new version of Refills

Future Refills will not depend on Neat. Components will be agnostic of any grid system.

**Comment by pixelminds** [comment]
So the final picture will be both Bitters and Refills depending only on Bourbon, and Neat as a standalone grid system. That will make it less confusing, despite the fact that some people may swap Neat with Susy or else. Thumbs up for that path, anyway.

**Comment by tysongach** [comment]
> So the final picture will be both Bitters and Refills depending only on Bourbon, and Neat as a standalone grid system.

Bingo.

**Comment by tipoqueno** [comment]
@tysongach Can we help with any thing? I really love the way that Bourbon and Neat works and want to have the 5.0 release.

**Comment by ottobyte** [comment]
Glad to hear it's still in progress. Like others I love the Bourbon libraries - they are always there for me to start off with!

**Comment by mr-bjerre** [comment]
I am new to the game but have been investigating quite a bit on how to setup my framework for developing a new site. I came to the conclusion that I'd use Bourbon, Neat, Bitters and maybe even some Refills, but then I stumbled upon this whole 4 vs. 5 version issue.

I don't like the idea of implementing deprecated mixins etc. but I'd really miss the documentation if I start on the current master branch - especially when I am new to the game. My question is quite simple; what do you recommend for a new project?

**Comment by tysongach** [comment]
@mr-bjerre You can find the WIP 5.0 docs here: http://bourbon.netlify.com/docs/latest/

While it may appear that we are removing lots of features in 5.0, almost all of the removals go back to just one big change we are making, which is that we will no longer going to have mixins for prefixing CSS. So, if you choose to use 4.3, don't use any of the deprecated mixins for prefixing and you'll be fine. If you want to use the latest Bitters, you need to use Bourbon 5, which is also a fine route to go.

**Comment by tysongach** [comment]
@tipoqueno We just need to wrap up the docs site and look into a few reports of issues within a Rails environment and we should be good to go. I’m planning to spend my [investment time](https://thoughtbot.com/playbook/our-company/time#investment) today working on those things 😉

**Comment by ottobyte** [comment]
Thank you very much for the links to the docs! Very helpful.

**Comment by bdkjones** [comment]
Great to hear there's some docs available!

I definitely take the point about this being a free project. It's just that the decision to up the dependency to 5.0 for some other frameworks but not actually *ship* 5.0 left a lot of things in limbo.

**Comment by skube** [comment]
So am I correct in understanding, if I want to use Neat 2.0 today I don't need to depend on anything else (other than SASS)?

**Comment by tysongach** [comment]
@skube Yes, that is correct. You can also check the “Requirements“ list in Neat’s readme: https://github.com/thoughtbot/neat#requirements.

**Comment by tysongach** [comment]
I’m going to close this because it has no action item. Hopefully we’ve cleared up a few things and answered some questions.

We also just released Beta 8, which hopefully resolves our outstanding issues with Bourbon and Rails and puts us in a much better place to cut the final release.

Thanks for the patience, everyone!
