### ISSUE TITLE
Tint percent is upside down

### ISSUE THREAD

**Issue by JulianSteinmann** [thoughtbot/bourbon#1070]
100% tint generally means that it is the full colour and 0% tint is white. 
Indesign for example uses tint this way. 
Bourbon has it the other way around: 0% -> full color   –   100% -> white

This:
@return mix(#fff, $color, $percent);
Should be:
@return mix(#fff, $color, 100% - $percent);

**Comment by Toddses** [comment]
Per the docs, this is the correct behavior for `tint`.

https://www.bourbon.io/docs/5.1.0/#tint

Basically, tint `Mixes a color with white.` and so, the behavior you're seeing is the expected behavior. Mix 0% of white with the given color, you get the full color returned.

**Comment by Toddses** [comment]
Duplicating the mixin to return the value you'd like is probably your best play here. You might be right that tools like InDesign use tint the way you describe, but Bourbon is a mixin library, not a fully-featured design tool. Considering changing the behavior of `tint` in Bourbon is a breaking change, it is unlikely to get very far.

Luckily, Bourbon is open source and it should be very easy to duplicate and modify the return value.

**Comment by tysongach** [comment]
As @Toddses said, the `tint` function mixes white _into_ a color, and the `$percent` argument represents the quantity of white to be mixed in.

You mentioned InDesign, which is primarily a tool for creating printed materials. Perhaps the reason it calculates tint differently is because it operates in the CMYK (subractive) space, but in screen design we’re working in the RGB (additive) space?

I imagine another reason the function is setup this way, is to be consistent with other Sass libraries and frameworks. For example, [Compass also had a `tint` function](http://compass-style.org/reference/compass/helpers/colors/#tint), and it’s `$percentage` argument functioned the same way. This [CSS-Tricks article](https://css-tricks.com/snippets/sass/tint-shade-functions/) also details functions that work this way.

**Comment by Toddses** [comment]
Sorry I deleted that comment. :) After rereading the post, I got the feeling Julian understood the documented behavior and was suggesting it be changed, so I offered an alternate idea.

**Comment by JulianSteinmann** [comment]
**@tysongach** Yes that true, that's a good point with RGB / CMYK and the consistency with other frameworks.

I kind of wondered myself, while I was writing this, if this is really worth highlighting. As even if this were done upside down unintentionally – by now everyone who is using this likely already gotten used to the way it is now... I just mainly wondered if I am the only one who thinks this is weird =)

**Comment by tysongach** [comment]
> Considering changing the behavior of `tint` in Bourbon is a breaking change, it is unlikely to get very far.

I’d encourage us to refrain from creating an atmosphere where we depress questions and ideas based on breaking changes, or our process for dealing with that. I think it’s healthy to leave that door open and have discussions; it’s very possible we didn’t build something right the first time. We have [Semantic Versioning](https://semver.org/) to lean on for releasing breaking changes.

> I kind of wondered myself, while I was writing this, if this is really worth highlighting.

Yes, it is! Continuing on my comment just above, I hope that by you opening this issue, we all now have a better understanding as to why the function is designed the way it is.
