### ISSUE TITLE
Remove TTF / OTF on Bourbon 7!

### ISSUE THREAD

**Issue by Gouigouix** [thoughtbot/bourbon#1100]
## Description
**Why remove TTF / OTF font format ?** Today there are many still doing only TTF, which are not converted to WOFF!

## Steps to Reproduce
```
@include font-face("custom-regular", "my-custom-font-regular", ("ttf")) {
  font-style: normal; font-weight: 400;
}
```

## Development Environment
- Bourbon version: 7
- Platform: Windows 10 64 bits

**Comment by tysongach** [comment]
> Why remove TTF / OTF font format ?

The primary driver is because WOFF and WOFF2 are well-supported across browsers:

- [Can I use... WOFF](https://caniuse.com/#feat=woff)
- [Can I use... WOFF2](https://caniuse.com/#feat=woff2)

Bourbon’s official browser support is [documented in the readme](https://github.com/thoughtbot/bourbon#browser-support) and WOFF/WOFF2 support falls well within that.

I think it’s also worth noting that WOFF is designed specifically for the web and comes with performance benefits over older formats like OTF and TTF (especially WOFF2). By removing support for old formats, maybe we can nudge folks to start using WOFF/WOFF2.

That said, I understand that not everyone can switch to WOFF immediately. Bourbon 6.0 is stable and continues to be available. You can lock your project to v6.0 like so:

In your `package.json` for npm/Yarn:

```json
"dependencies": {
  "bourbon": "6.0.0"
}
```

In your Gemfile:

```ruby
gem "bourbon", "6.0.0"
```

**Comment by tysongach** [comment]
@Gouigouix Anything else I can help with?
