### ISSUE TITLE
sass indented syntax instead of scss

### ISSUE THREAD

**Issue by gercheq** [thoughtbot/bourbon#296]
Is the indented syntax supported? What's the best way to convert scss files into indented syntax? Thanks!

**Comment by j-walker23** [comment]
@javaporter Finally!!!! First time i have ever heard anyone say any reason why .sass is cleaner/nicer then .scss. My mind has been blown ever since i found out that people would rather Sass be compatible with vanilla css then have it be a nice clean implementation.

No need for braces or @include, inheritance is inferred from indenting, like all GOOOOD programmers already do in their code.

Is this weird to anyone else? I am not sure i'll ever get it. So what, I can't paste in vanilla css to my .sass file. But i can hit a website and convert it and paste it in then. 

Makes me sad that the Sass guys had a nice clean awesome .sass api and then switched to .scss and everyone followed suit. Why guys, why!

Sorry for the rant, this had bugged me randomly for a couple of years lol.
