### ISSUE TITLE
ellipsis mixing: make the display property a parameter

### ISSUE THREAD

**Issue by didoo** [thoughtbot/bourbon#634]
Normally I use the ellipsis on text that stands on a single line on its own, so it's not clear to me why the mixin uses display: inline-block. My suggestion is to have at least the property as a parameter that can be overwritten when the mixin is used/included.

**Comment by tysongach** [comment]
Having `display: inline-block` included means that this mixin can be used for inline elements, e.g. a `span`. Since we turn off `word-wrap` as part of this mixin, the text will be on only one line.

I’m not sure I fully understand your use-case. Do you have a CodePen or something to show an example?
