### ISSUE TITLE
transition-property doesn't respect global prefixer options

### ISSUE THREAD

**Issue by jacobbuck** [thoughtbot/bourbon#637]
If I set

```
$prefix-for-webkit: false;
$prefix-for-mozilla: false;
```

then

```
@include transition-property(border-color, color);
```

still outputs

```
-webkit-transition-property: border-color, color;
-moz-transition-property: border-color, color;
transition-property: border-color, color;
```

:disappointed:

**Comment by joshuaogle** [comment]
Hi Jacob,
I put together a fix in #638. Looks like that one never got switched over to using the prefixer for some reason. That should sort it out for you.

**Comment by jacobbuck** [comment]
:+1:

**Comment by tysongach** [comment]
Unfortunately, Josh and I figured out the the transition mixin would need much more of a rewrite and not just a quick fix to stop these prefixes from being output. We realize keeping track of these prefixes is a huge task, which is why we are [no longer doing this in v5.0](https://github.com/thoughtbot/bourbon/issues/702). I would highly recommend you check out [Autoprefixer](https://github.com/postcss/autoprefixer) as another solution, rather than our prefix mixins.
