### ISSUE TITLE
Question:  Error: @charset may only be used at the root of a document.

### ISSUE THREAD

**Issue by suisho** [thoughtbot/bourbon#687]
I update bourbon 4.2.1 and got error  `Error: @charset may only be used at the root of a document.`

Can I resolve this error?

**Comment by tysongach** [comment]
How are you compiling the Sass? What’s your dev environment?

**Comment by suisho** [comment]
Sorry for lack information.
This is my environment.

```
% ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

% sass -v
Sass 3.4.12 (Selective Steve)

% npm ls | grep sass
├─┬ grunt-contrib-sass@0.8.1
```

Updating command is like this

```
bourbon update --path=./sass/core/lib/
```

and I compile with grunt

```Gruntfile.js
sass: {
  dist: {
    options :{
      sourcemap: 'none',
      style : 'expanded',
      loadPath : ['sass'],
    },
    files: [{
      expand: true,
      cwd: 'sass',
      src: ['**/*.scss'],
      dest: 'web/css',
      ext: '.css'
    }]
  }
},
```
and use import like this

```application.scss
@import "core/lib/bourbon/bourbon";
```

**Comment by shepmaster** [comment]
We are seeing a similar problem. Our SCSS looks like

```scss
.embedded-container {
  @import "bourbon";
}
```

In our case, we are producing HTML / CSS that gets embedded in another site, so we want to make sure that *all* of our CSS is scoped to our container. For now, we can remain at version 4.0.2, but it'd be nice to know if it's possible to work around this

**Comment by tbremer** [comment]
I am curious as to why `@charset 'UTF-8'` was added to every file as well. @tysongach?

**Comment by kitop** [comment]
Same issue here. Why was that added?
Isn't bourbon supposed to be a mixin library, and not produce any output?

**Comment by tysongach** [comment]
@tbremer @kitop How are you both compiling your Sass?

These `@charset`’s were added so that we can use special characters in our source code. We are currently moving towards adding Bourbon’s documentation to the source of each mixin, so that it can be versioned and generated more easily.

It’s possible that we only need the `@charset` declaration on our main manifest: `_bourbon.scss`

**Comment by kitop** [comment]
@tysongach I'm just using Rails' asset pipeline. My error was because a mixin file (that imported bourbon) was imported inside another CSS rule (`.foo { @import 'mixins' }`) which I fixed now. 

I see the point of adding the `@charset` anyway, just wish scss had another way to do that to eliminate the extra output.

**Comment by tysongach** [comment]
@suisho @shepmaster This issue appears to be tied to importing Bourbon inside another CSS rule. Are you both doing that? If so, is there a specific reason your imported within another rule?

**Comment by shepmaster** [comment]
@tysongach yep! I attempted to [explain *why* in my earlier comment](https://github.com/thoughtbot/bourbon/issues/687#issuecomment-77217379). Let me know what more you'd like me to explain.

**Comment by tysongach** [comment]
@shepmaster I’m not sure I understand the purpose of importing within `.embedded-container`. Bourbon is a library of mixins and functions and doesn’t output _any_ styles on its own.

The scoping you mentioned is not actually scoping Bourbon to that class. Instead, you should be able to move the `@import` for Bourbon outside of that rule, then _use_ Bourbon’s features within the class.

Have you tried moving the `@import` for Bourbon outside of that class already? Does it resolve the issue?

**Comment by shepmaster** [comment]
@tysongach that's... an excellent point. I'll have to dig into it tomorrow at work, to understand why it was originally put there!

**Comment by tysongach** [comment]
@shepmaster Any update?

@suisho Please see comments above. Are you still having issues? Are you nesting imports?

**Comment by suisho** [comment]
Sorry for I miss out mentioned.

I found use nesting import too.
And this problem is occurred because my sass directory structure...
(I wrap and important `main.scss` file for design style guide.)

My problem is not resolved perfectly, but may can it.
Thank you.

**Comment by shepmaster** [comment]
@tysongach While we still aren't able to un-nest Bourbon, I don't think that it's Bourbons fault. Unfortunately for us, we use both Bootstrap and Bourbon, and these two projects have conflicting mixin names (like `text-hide`). We were importing Bourbon *after* Bootstrap to use the version from Bourbon, but Bootstrap needs to be nested so that the classes it creates are scoped appropriately. It seems we have gotten ourselves into a pickle! Any hints or advice would be appreciated, but I think that Bourbon is doing the right thing. Thanks for your hard work!

**Comment by tysongach** [comment]
@shepmaster Thanks for the update. Unfortunately, I really don’t have any insight on how to solve your issue; a pickle indeed.

I’m unclear on how you’re using Bootstrap, but maybe try to remove any conflicts (e.g. the `hide-text`) by not importing those pieces of Bootstrap, so that then Bourbon can be imported before…

**Comment by marciovicente** [comment]
Are you trying import bourbon as a css rule?
Like: 
```scss
.some-class { @import "bourbon"; }
````

It get the same error and when I fix this import, it's works fine.

**Comment by wardpenney** [comment]
Advise to not `@import "bourbon";` from within a rule. There is no need to do so (you don't need to nest non-rendering SASS).
