### ISSUE TITLE
Addition to $all-buttons Variable

### ISSUE THREAD

**Issue by cesize** [thoughtbot/bourbon#697]
I really like the `$all-buttons` variable, but I was wondering if it's possible to add a `$all-buttons-visited` variation, as this is a commonly used alter-state.

I'm running into a problem overwriting existing styles and have no way to assign `:visited` to this catch-all variable.

Forgive me, as I'm not exactly a SASS power-user and I don't fully comprehend its capabilities and limitations, but while writing this I also wondered whether it might be possible to do something that would enable us to "extend" this variable with our own classes (or even other pseudo-classes like `:first-of-type`) so that they would cascade down with the variations.

For example, I need to include a number of extra classes for my "all buttons" selector list. (Again, overwriting other styles... sigh).  It's a pain to also have to add each of these to the hover, focus, and active selector lists.

**Comment by tysongach** [comment]
I’m not sure I fully understand your use-case and issue, but the `:visited` CSS pseudo-class is [for use on links](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited), i.e. `<a href="http://bourbon.io">Bourbon</a>`.

Bourbon’s `$all-buttons` variable [outputs](http://bourbon.io/docs/#buttons-variable) `button` and `input` elements, but no `a` elements. Since `button`’s are [not used for links](https://css-tricks.com/use-button-element), I don’t believe a `:visited` variation is correct here.

**Comment by cesize** [comment]
Because ".button" is included, and ".button:visited" could be valid...

The addition would make more sense if I had made my latter suggestion the primary request.  So, how about the ability to customize (pass in) additional button definitions so we can use the sub-variables?

**Comment by tysongach** [comment]
`.button` is not included, just the `button` element: http://bourbon.io/docs/#buttons-variable

**Comment by cesize** [comment]
Forgive me, it's been a long day... I'm looking at fairly repetitive lines from multiple sources/authors and one looked an awful lot like another one in which I am using the var.  If you'll excuse me, I need to go crawl in a hole and die now.
