### ISSUE TITLE
Should _font-family.scss variables be more generic?

### ISSUE THREAD

**Issue by bobrocke** [thoughtbot/bourbon#709]
Would it be better form to use variables such as $serif and $sanserif instead of $georgia and $helvetica? That's already done with $monospace, for example.

Overriding those variables becomes more semantic and generic that way.

**Comment by tysongach** [comment]
That’s a great question.

I think `$georgia` and `$helvetica` are great because you know what font stack you’ll get when using that. But I do think it’s strange that we’re not being consistent; e.g. `$monospace` doesn’t indicate what font stack is actually used.

I’m going to investigate cleaning this up for 5.0. Thanks!

**Comment by tysongach** [comment]
The following has been added to v5.0:

```scss
$consolas: "Consolas", "monaco", monospace;
$courier-new: "Courier New", "Courier", "Lucida Sans Typewriter", "Lucida Typewriter", monospace;
$monaco: "monaco", "Consolas", "Lucida Console", monospace;
```

These will replace the `$monospace` variable that we currently have.

Thanks for your input!
