### ISSUE TITLE
css Error issue...

### ISSUE THREAD

**Issue by mslfire** [thoughtbot/bourbon#718]
Not sure what is wrong -new to sass and bourbon - I have Scout set-up with bourbon gem and files on my project when I change my main.scss file I get a error -
--bourbon/helpers/_font-source-declaration.scss
error main.scss (Line 22 of _font-source-declaration.scss: Invalid CSS after " eot)": expected "}", was ": "#{$file-path...")
identical main.css 
This a new file not changed by me. Anyone know whats up here?

**Comment by tysongach** [comment]
What version of Sass is being used?

**Comment by mslfire** [comment]
truthfully I am not sure - just downloaded latest - Is there a way to find out?

**Comment by tysongach** [comment]
If you installed Sass via the command line, you can run `sass -v`. The latest version of Bourbon (4.2.2) requires Sass 3.4+.

However if you’re using Scout app to compile your Sass, it [appears](https://github.com/mhs/scout-app) that it is very out of date and uses an old version Sass (3.2). If this is the case, then it will not work with Bourbon 4+. You will have to downgrade to Bourbon 3.2.4 to work with Sass 3.2.

**Comment by mslfire** [comment]
Ok - thanks tyson! The reason I'm using Scout is im more of a designer (like shiny things) and not that comfortable with command line. I want to begin to use bourbon what is the best (good) way to use set it up? I want to get away from bootstrap... 
What would you suggest as a working platform? If not Scout... 
 - I'm using Windows operating system. 
 -Want to stay away from command line if possible.
 -want to use neat, bitters, refills as well

**Comment by mslfire** [comment]
Wow - I have also tried using prepros - did not really like idea of downgrading to 2012 and still the same css error. Could this be issue more with bourbon then scout or prepros? here is error log in prepros 

Error: Invalid CSS after "    eot)": expected "}", was ": "#{$file-path..."
        on line 22 of bourbon/helpers/_font-source-declaration.scss
        from line 28 of bourbon/_bourbon.scss
        from line 2 of main.scss
  Use --trace for backtrace.

**Comment by tysongach** [comment]
This error is usually due to a version issue between Sass/LibSass and Bourbon. When using these GUI tools like Prepros or Scout, they are commonly packaged with a specific version of Sass/LibSass. You’ll have to know what version they use to compile Sass and then make sure it’s compatible with Bourbon.

Poking around the Prepros website, it looks like it might use LibSass to compile, but I don’t see which version it is packaged with. The latest version of Bourbon require LibSass 3.1+, so if it’s packaged with a version of LibSass prior to this, it could be causing this error.

Can you look in the Prepross app itself and see which version of Sass/LibSass it is using?

Although you said you didn’t want to use the command line, it usually is the easiest and quickest way to use Bourbon and Sass. I would highly recommend getting comfortable with it. I’m a designer too and can honestly say that learning the command line is one of the best moves I made and it really doesn’t take long to learn the basics.
