### ISSUE TITLE
[V5] About appearance mixin

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/bourbon#727]
This is probably not a good idea to include an `appearance` mixin in v5, or basically a mixin for any property not prefixed by Autoprefixer. This for a couple of reasons:

* there are reasons why Autoprefixer does not prefix those properties;
* Autoprefixer might evolve and prefix those properties, making Bourbon forced to deprecate its mixins sooner or later;
* if a new prefixed version for those properties comes to appear, Bourbon would have to update its mixins which defeats the purpose of dropping CSS prefixing in v5;
* Bourbon v5 does not provide custom prefixing mixin anymore, only the `prefixer` helper, so it makes no sense to draw an exception for some properties, especially since it makes everything more confusing.

My 2 cents.

**Comment by kaishin** [comment]
> there are reasons why Autoprefixer does not prefix those properties

Can you elaborate?

**Comment by tysongach** [comment]
@HugoGiraudel We did initially plan to keep it, but we’ve decided to remove it. The thing is, we actually _use_ that mixin _a lot_. While it (was) non-standard, it’s value is high for when we build products.

Autoprefixer didn’t support it because it was non-standard. However, as of a few weeks ago, `appearance` was put back on the standards track and Autoprefixer has openly stated it will be supported in v5.2.

As always, thinks for your thoughts and ideas, Hugo!! They are appreciated.

:tada:

**Comment by HugoGiraudel** [comment]
Oh. Cool then. :)
