### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by ajmerainfo** [thoughtbot/bourbon#766]
When I use below line from doc. getting error below.

```scss
@include background(linear-gradient(red, green) left repeat);
```

Error:
```
Error in plugin 'gulp-sass'
Message:
    node_modules\node-bourbon\node_modules\bourbon\app\assets\stylesheets\helpers\_linear-gradient-parser.scss
  11:23  argument `$string` of `str-index($string, $substring)` must be a string
Backtrace:
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:11, in function `str-index`
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:11, in function `_linear-gradient-parser`
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:27, in mixin `background`
	component/sass/_layout.scss:75
Details:
    column: 23
    line: 11
    file: C:/Users/Keyur/Documents/Projects/BourBon/BourbonTest/src/BourbonTest/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss
    status: 1
    messageFormatted: node_modules\node-bourbon\node_modules\bourbon\app\assets\stylesheets\helpers\_linear-gradient-parser.scss
  11:23  argument `$string` of `str-index($string, $substring)` must be a string
Backtrace:
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:11, in function `str-index`
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:11, in function `_linear-gradient-parser`
	node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:27, in mixin `background`
	component/sass/_layout.scss:75
```

**Comment by mehlah** [comment]
this line shouldn't throw an error. Double checked in this CodePen http://codepen.io/mehlah/pen/bVbyJr
Which version of Bourbon are you using?

**Comment by ajmerainfo** [comment]
That link's code working perfectly fine with all browser. 
I am using below version with gulp. and it's give me error. 
```
"gulp-sass": "^2.0.4"
"node-bourbon": "4.2.3"
"node-neat": "^1.7.2"
```

**Comment by mehlah** [comment]
Okay, this might be an issue with LibSass.
To be sure, can you please use `gulp-ruby-sass` instead of `gulp-sass` to confirm if it's working correctly?

If you want to keep using LibSass with `gulp-sass`, you can use the `background-image` mixin as a workaround to get the correct CSS output:

```sass    
@include background-image(linear-gradient(red, green));
```
I'll take a look to Bourbon's code for fixing it.

**Comment by tysongach** [comment]
Related: #729.

This is an issue specific to LibSass. Couple things, though:

1. If you’re using the mixin for the prefixing, browser support for gradients [is pretty damn good](http://caniuse.com/#feat=css-gradients), so you may not even need prefixing or need to use this mixin at all. If you do need prefixes, [use Autoprefixer instead of Bourbon](https://github.com/thoughtbot/bourbon/issues/702).

2. Try this syntax:

   ```scss
  @include background-image(linear-gradient(to bottom, red, green));
  ```

We don’t have a quick fix and we know these mixins are quite fragile when used alongside LibSass. Truthfully, I’d suggest Autoprefixer if you really need the prefixing.

**Comment by ajmerainfo** [comment]
Thank you so much "mehlah" & "tysongach".
I tried below code 
```
@include background-image(linear-gradient(red, green));
```
and it's work great.
