### ISSUE TITLE
Gradients' errors with libSass

### ISSUE THREAD

**Issue by gambala** [thoughtbot/bourbon#767]
I get various errors when use linear-gradient, radial-gradient or background-image mixins with libSass (Rails 4.2.4, sassc-rails 1.1.0, bourbon 4.2.4)

----

this code:

```sass
@import 'css3/background-image'
+background-image(linear-gradient(white 0, yellow 50%, transparent 50%))
```

gives me an error:

```
Error: argument `$map` of `map-get($map, $key)` must be a map

       Backtrace:
       	../../.rvm/gems/ruby-2.2.2/gems/bourbon-4.2.4/app/assets/stylesheets/css3/_background-image.scss:25, in function `map-get`
       	../../.rvm/gems/ruby-2.2.2/gems/bourbon-4.2.4/app/assets/stylesheets/css3/_background-image.scss:25, in mixin `background-image`
       	app/assets/stylesheets/web-teplitsa/pages.sass:53
        on line 25 of ../../.rvm/gems/ruby-2.2.2/gems/bourbon-4.2.4/app/assets/stylesheets/css3/_background-image.scss
>>         $webkit-image:  map-get($gradients, webkit-image);
   ------------------------^
```

----

this code:

```sass
@import 'css3/linear-gradient'
+linear-gradient(#fff, #e9e9e9)
```

works well on development, but gives me an error through assets compilation:

```
SassC::SyntaxError: Error: error reading values after ,
        on line 9315 of stdin
>> ound-image: linear-gradient(#fff, #e9e9e9, , , , , , , , );
   ------------------------------------------^

  (in /home/gambala/git/livsites/app/assets/stylesheets/web-teplitsa.sass)/home/gambala/.rvm/gems/ruby-2.2.2/gems/sassc-1.6.0/lib/sassc/engine.rb:38:in `render'
```

----

this code:

```sass
@import 'css3/radial-gradient'
+radial-gradient(#1e5799, #3dc3d1)
```

gives an error:

```
Error: index out of bounds for `nth($list, $n)`
        on line 13 of ../../.rvm/gems/ruby-2.2.2/gems/bourbon-4.2.4/app/assets/stylesheets/css3/_radial-gradient.scss
>>   $g2:  nth($data, 2);
   --------^
```

----

I really want to use libSass instead of Sass because of 10X faster compilation speed.

**Comment by mehlah** [comment]
Thanks @gambala for your report.
Those are mostly issues with current LibSass implementations.
For example `@include linear-gradient(#fff, #e9e9e9)` outputs `background-image: linear-gradient(#fff, #e9e9e9, , , , , , , , );` when using LibSass, because LibSass doesn't remove `null` values from lists before interpolating in CSS strings.
This has [already been fixed](https://github.com/sass/libsass/pull/1389) in LibSass but planned for 3.3.

I don't know what is Bourbon's team take on this.
Should we fix those tiny bits when possible by removing null values ourselves for example, or wait for the next LibSass release and bump Bourbon's requirements?
Note that all those `background` mixins will be removed in Bourbon 5 (first alpha released a couple days ago)
/cc @tysongach

**Comment by tysongach** [comment]
Related: #729.

It does appear to be an issue with LibSass, as @mehlah pointed out, and we’re anxiously awaiting for `3.3` to be released.

Couple things, though:

1. If you’re using the mixin for the prefixing, browser support for gradients [is pretty damn good](http://caniuse.com/#feat=css-gradients), so you may not even need prefixing or need to use this mixin at all. If you do need prefixes, [use Autoprefixer instead of Bourbon](https://github.com/thoughtbot/bourbon/issues/702).

2. For an intermediate fix, try passing a position to the mixin (typically optional, but with LibSass it seems to fix things):

  ```sass
  +background-image(linear-gradient(to top, white 0, yellow 50%, transparent 50%))
  ```

  _Note the `to top` part (adjust to which ever direction you need)_. This works for me.

  And for the radial gradient, try:

  ```sass
  +background-image(radial-gradient(#1e5799, #3dc3d1));
  ```

We don’t have a quick fix and we know these mixins are quite fragile when used alongside LibSass. Truthfully, I’d suggest Autoprefixer if you really need the prefixing.
