### ISSUE TITLE
flex-grid

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/bourbon#770]
hello
I'm a little confused when it comes to flex-grid - is this going to stay or is it going to be removed at all - I read that it is going to be depreciated in bourbon and moved over to neat - does that mean the functions are going to stay for good but as part of neat.

please clarify.

Thanks

**Comment by tysongach** [comment]
Hi!

Yes, we deprecated the [`flex-grid`](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss#L378) functions in Bourbon in favor of them being part of Neat, instead. Bourbon throws a warning for now, but they will be fully removed and no longer available as of `5.0`.

**Comment by tysongach** [comment]
The deprecation of these functions are here in Bourbon only. When we deprecated them here, we moved them to Neat because we felt like Neat was a better home for _all_ grid-related features; rather than Bourbon.

So at least for now, the `flex-grid` functions are in Neat and they will _not_ be deprecated there.

**Comment by mmjaeger** [comment]
got it - thanks

**Comment by tysongach** [comment]
Yes, but it’s un-documented.
