### ISSUE TITLE
radial-gradient doesn't work on chrome

### ISSUE THREAD

**Issue by kazkovsky** [thoughtbot/bourbon#793]
Hey, 

```@include radial-gradient(#1e5799, #3dc3d1);```

 produces:

```background-color: #1e5799;
    background-image: -webkit-radial-gradient(#1e5799, #3dc3d1, , , , , , , , );
    background-image: radial-gradient( #1e5799, #3dc3d1, , , , , , , , );```

which is invalid syntax for Chrome (version 45)

**Comment by elomatreb** [comment]
This is probably an issue that occurs when using libsass. See #729 for more information.

**Comment by tysongach** [comment]
@kazkovsky Are you compiling with LibSass? If not, can you provide more details regarding your dev environment?

Also: are you sure you still need prefixes? Support for gradients these days is pretty strong: http://caniuse.com/#feat=css-gradients

I would use Autoprefixer, instead of Bourbon, if you do indeed need prefixes…

**Comment by jareware** [comment]
I'm also compiling with libsass, and can confirm linear gradients not always work on Firefox even if they work on Chrome and Safari.

**Comment by tysongach** [comment]
Personally, I’d use Autoprefixer if you’re looking to prefix your gradients. But you can find a workaround for Bourbon via my comments in both #767 & #729.

**Comment by jareware** [comment]
Oh, I didn't realize vendor-prefixing was out of scope for Bourbon..?

**Comment by tysongach** [comment]
@jareware We are removing them in v5: https://github.com/thoughtbot/bourbon/issues/702

**Comment by jareware** [comment]
Ah, solid reasoning, :+1:!
