### ISSUE TITLE
calc() in @media ?

### ISSUE THREAD

**Issue by radubogdan** [thoughtbot/bourbon#809]
I recall that this syntax was working. Am I wrong? 

```scss
@include media(min-width 25em max-width calc(50em - 1px)) {
  ....
}
```

The code from above compiles to and the browser fails to display styles:

```css
@media screen and (min-width: 25em) and (max-width: calc(50em - 1px)) {
  ....
}
```

Bourbon: 4.2.5
Sass: 3.4.19
Sass-rails: 5.0.4

This results in a ParseError for CSS.

- [W3 Media queries](http://www.w3.org/TR/css3-mediaqueries/#media1)
  - Properties may accept more complex values, e.g., calculations that involve several other values

**Comment by tysongach** [comment]
Hi! `media()` is actually a feature of Neat, not Bourbon.

But after digging into this a little, it just boils down to CSS and the fact that `calc()` is actually _not_ supported inside media queries. The wording in that W3C document is a bit poor, because it does make it sound like it is. They should make that more clear.

It’s hard to find specific evidence of this, but two things that helped me discover this is:

1. http://peterwilson.cc/media-queries-calc/
  - “Checked Jan 20, 2015 against Chrome 39, Firefox 34 & Safari 8 on OSX”
2. Here’s a CodePen which has three checks: http://codepen.io/tysongach/pen/gPWvEm?editors=110
  1. `Test 1` – Pure CSS (not using Neat); this fails, as the text color never changes to green
  2. `Test 2` – Uses Neat’s `media()` feature (exactly what you have above); this fails, as the text color never changes to green
  3. `Test 3` – Pure CSS, but no use of `calc()` in the media query; this _passes_ and the text color changes to green between `25em` and `50em` (though obviously this doesn't solve you need for using `calc()` in the first place)

So at the end of the day, Neat is correctly outputting the CSS, as it should (likely) be written for a media query with a `calc()` value.

Hopefully this is supported some day! Would be quite useful.
