### ISSUE TITLE
add support for position:sticky to the position mixin

### ISSUE THREAD

**Issue by raorao** [thoughtbot/bourbon#853]
current, safari requires the `-webkit-` prefix to implement `position: sticky`. That is not currently supported by bourbon

**Comment by joshuaogle** [comment]
We are [switching to Autoprefixer](https://github.com/thoughtbot/bourbon/issues/702) to handle vendor prefixing like `-webkit-`. You can currently use sticky in the `position` mixin and Autoprefixer will prefix it for you. Since v5.0 will be out very shortly with that feature, we won't be adding it in the mixin itself. If you aren't using Autoprefixer in your project currently, give it a try!
