### ISSUE TITLE
Overriding bourbon defaults in local file

### ISSUE THREAD

**Issue by raratiru** [thoughtbot/bourbon#867]
I received the most recent update.

Is there a way to override the default settings in my local ```_variables.scss``` in order to keep all my settings together?

This file is imported last, and I tried for example the following:

```$bourbon: ("modular-scale-ratio": 1.2, ) !default;```
or
```$modular-scale-ratio: 1.2;```

I had no success, whatsoever. 

The result is good only if I place my changes in ```bourbon/bourbon/settings/_settings.scss```

**Comment by tysongach** [comment]
Hi! Yes, you should be able to declare your own default settings via the `$bourbon` map in your `_variables.scss` file. You shouldn’t need the `!default` flag as you have above, since you are actually wanting to _override_ the defaults.

Is this code open-source somewhere that I can see it? Or can you provide your Sass manifest file?

**Comment by raratiru** [comment]
OK ... 

Thank you for the prompt response. Indeed it works great. 

I had many consoles open simultaneously and the most probable is that I mixed up environments and/or repositories. Too tired...

Thank you again!

**Comment by tysongach** [comment]
@raratiru Glad you got it sorted out!
