### ISSUE TITLE
How do I avoid the warning - `overflow-scrolling` appears to be spelled incorrectly

### ISSUE THREAD

**Issue by veeracs** [thoughtbot/bourbon#876]
I don't think it is misspelled, but again there's no mixin for overflow-scrolling?

```
-webkit-overflow-scrolling: touch;
```

**Comment by tysongach** [comment]
@veeracs Hi! I’m not sure I understand your question. Are you getting a warning when using a Bourbon mixin? `-webkit-overflow-scrolling` _is_ non-standard, but is used for momentum-based scrolling on iOS. That being said, it’s not used anywhere in Bourbon and we won’t be adding it as its own mixin, since [we’re moving away from mixins for prefixing](https://github.com/thoughtbot/bourbon/issues/702).

**Comment by veeracs** [comment]
Ok thanks for the update @tysongach, closing this issue...
