### ISSUE TITLE
@include background

### ISSUE THREAD

**Issue by andering** [thoughtbot/bourbon#880]
I noticed background mixin was removed, is it bug or feature ?

Thanks.

**Comment by tysongach** [comment]
Hi @andering! You’re speaking about it being removed in v5.0, yes? If so, it was removed because we are [no longer supporting mixins for applying vendor prefixes](https://github.com/thoughtbot/bourbon/issues/702) (Autoprefixer is a much better tool for this, if needed). Also note that [linear gradients are well supported](http://caniuse.com/#feat=css-gradients) these days, so it’s quite possible you don’t need prefixes, at all.

**Comment by andering** [comment]
Thanks for reply. Not sure why but i thought @include background was doing more than prefixing.
Thanks.
