### ISSUE TITLE
gulp-sass compiling error with 'transition' mixin

### ISSUE THREAD

**Issue by oldirony** [thoughtbot/bourbon#889]
Hello,

when comping the scss code with gulp-sass (version 2.2.0) the mixin
`@include transition(transform 0.5s)`

is compiled to
`transition: transform;`
instead of 
`transition: transform 0.5s;`

The problem appears only when applying the transition to the **transform** property.

A workaround is to explicitly define the duration with 
`@include transition-duration(0.5s)`
but it cannot be a stable solution. 

Cheers

**Comment by tysongach** [comment]
@oldirony Hi! This is actually a bug in LibSass. I believe upgrading to LibSass 3.3.3 should resolve the issue (it does in my findings). That being said, there is a chain of reactions here, because: gulp-sass wraps node-sass which wraps LibSass. It looks like gulp-sass has a beta out, and I’d bet this packages a newer version of LibSass which should fix your problem.

Also, CSS transitions have _really_ great support these days; do you need prefixes? Here’s a compatibility chart: http://caniuse.com/#feat=css-transitions
