### ISSUE TITLE
marking something important!

### ISSUE THREAD

**Issue by MareoRaft** [thoughtbot/bourbon#900]
Hey All!

I'm thinking of using your cool Bourbon library in our website.  I wanted to do something like this:

    	@include calc(right, "#{$circle-diameter} + 10px") !important;

only to find out that I can't apply `!important` to the calculated `right` property like that.  Well I can't think of a way to add the important setting, so this makes Bourbon useless in important situations ;)

Kidding aside, it looks like you've done a really great job with this library.  Perhaps there is a clever way that you can add this feature to your library?  There could be some variable you pass into the mixin that would cause the `important!` setting to apply to all the properties in the mixin.

Thanks!
Mareo

**Comment by tysongach** [comment]
Hi @MareoRaft! Couple thoughts:

1. We’ve had a similar request before: https://github.com/thoughtbot/bourbon/issues/562.
2. I’m be curious to know _why_ you want to add an `!important` rule?
3. Our next major releases removes all prefixing mixins, including `calc`; [more on that here](https://github.com/thoughtbot/bourbon/issues/702).
4. [`calc` has great browser support](http://caniuse.com/#feat=calc) these days, are you sure you need prefixes?

**Comment by MareoRaft** [comment]
Thanks for the speedy response!  Here is my code:

    #logout-circle {
    	@extend .hover-circle-with-text;
    	top: 0;
    	right: 0;
    	opacity: 0;
    
    	transition: all 0.4s ease;
    }
    .logout-circle-out {
    	top: 40px !important;
    	right: 55px !important;
    	opacity: 0.5 !important;
    }

So under certain conditions on my website, the javascript will trigger `$("#logout-circle").addClass("logout-circle-out")`, which causes the top, right, and opacity of the logout circle to change, and animate.

For some reason, this needed `important!` to work, even though the `.logout-circle-out` appears UNDER the other CSS stuff.

Am I doing something wrong?  I appreciate any new CSS knowledge!  Thanks!

**Comment by tysongach** [comment]
@MareoRaft Ah! This looks like a classic case of specificity issues. Since ID selectors are _more specific_ than class selectors, your declarations within `#logout-circle` will overwrite the ones in `.logout-circle-out`, even though they precede them. You can read more about CSS specificity [over on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

I’d suggest either using all ID _or_ class selectors, instead of mixing them both. Personally, I stick with all class selectors; they can be used multiple times within a document and if you consistently use them, your styles will carry the same level of specificity.

Hope that helps!

**Comment by MareoRaft** [comment]
Thank you sir.  Very helpful article.  Using classes instead of IDs hasn't broken any of my jQuery code so far.  Very cool strategy.
