### ISSUE TITLE
Include box-flex mixin in flex-grow mixin, for better support of 2009 spec

### ISSUE THREAD

**Issue by mh-nichts** [thoughtbot/bourbon#908]
As I understand, box-flex is included in the flex (shorthand) mixin, but not in flex-grow (or flex-shrink).

The result is that when we use flex-grow as an include, box-flex is not included, so the "flexibility" doesn't work on Safari 5, for example.

Here is a test case :
http://codepen.io/mh-nichts/pen/wWowxy
The first list uses the flex short-hand, the second one uses only flex-grow.
On all modern browsers, both lists will behave the same : all items grow as needed.
However, in Safari 5 (desktop or iOS), only the second one behaves correctly : the first one doesn't have the box-flex (and the prefixed version), so the items don't grow as needed.

Maybe this decision of not including box-flex in flex-grow/shrink is a conscious one : if so, could you please explain me ?
Thanks in advance.

**Comment by tysongach** [comment]
Hi @mh-nichts!

[We only support Safari 6.1+ in Bourbon 4](https://github.com/thoughtbot/bourbon/tree/v4-stable#browser-support). We don’t support Safari 5 because the [current global usage is 0.06%](http://caniuse.com/usage-table) (0.10% for Safari 5.1).

It’s also worth noting that all prefixing mixins (including all of the flex ones) have been deprecated and removed in v5, which is our next release. Autoprefixer is a better tool for the job and you can target specific browsers to fit your project needs. More information on that can be found in #702.

**Comment by mh-nichts** [comment]
Thanks again for the explanation.
