### ISSUE TITLE
Flexbox : alternate value for justify-content: space-around for box-pack (2009 spec)

### ISSUE THREAD

**Issue by mh-nichts** [thoughtbot/bourbon#909]
I've seen the #527 merge and the #426 and #526 issues, which relate to the alternate value for -ms-flex-pack : it has been corrected for "distribute" in case of "space-around" for justify-content.

Currently, it's the same alternate value that is used for both flex-pack and box-pack in the justify-content mixin.
However, in the 2009 spec (box-pack), "distribute" doesn't exist : [the values can be either start / center / end / justify](https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack).
That means that, if we use "space-around", it will be compiled as "box-pack: distribute" and it will not work in browsers supporting the 2009 spec (ex : Safari 5 desktop and iOS) : the items are not evenly distributed, they stay aligned on the left.
Here is a test-case : http://codepen.io/mh-nichts/pen/GqNRgy

I suggest the alternate value for space-around should then be "justify" (same behaviour as in justify-content: space-between), so the items are at least evenly distributed, even if there is no space at the start and end.
That means the alternate value for box-pack would be different from the one for -ms-flex-pack :
- box-pack : justify
- -ms-flex-pack: distribute

**Comment by tysongach** [comment]
Hi @mh-nichts!

As mentioned in #908, [we only support Safari 6.1+ in Bourbon 4](https://github.com/thoughtbot/bourbon/tree/v4-stable#browser-support). We don’t support Safari 5 because the [current global usage is 0.06%](http://caniuse.com/usage-table) (0.10% for Safari 5.1).

I’d suggest using Autoprefixer, which is a better tool for the job and you can target specific browsers to fit your project needs.

**Comment by mh-nichts** [comment]
Thanks for the explanation, sorry for not reading carefully the browser support list.

**Comment by tysongach** [comment]
@mh-nichts No worries! Always here to help, if you need anything.
