### ISSUE TITLE
Error: no mixin named xy after bourbon import

### ISSUE THREAD

**Issue by flipflap** [thoughtbot/bourbon#977]
I am not sure if this is a CodeKit or bourbon issue. I am asking on both:
https://github.com/bdkjones/CodeKit/issues/271

### Expected behavior
bourvon Mixin should work

### Actual behavior
Get error for all mixins: **Libsass: Error: no mixin named linear-gradient**

### Steps to reproduce behavior
Installed bourbon via CodeKit. Added @import "bourbon";

### Bourbon version
Bourbon 5.0.0-beta.7

### Environment info
CodeKit on macOS Sierra, MAMP

**Comment by tysongach** [comment]
Hi @flipflap!

Are you upgrading from a previous version of Bourbon? If so, note that the `linear-gradient` mixin has been removed in `5.0` (`5.0.0.alpha.0`, specifically). You can see all changes, including deprecations and removals, in our Change Log: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md.

The mixin was only adding vendor prefixes. Since CSS gradients are [widely supported](http://caniuse.com/#feat=css-gradients) these days, it might be worth seeing if you need prefixes at all.

**Comment by flipflap** [comment]
Thanks tysongach, but no, it is a new project and none of the mixing works and adding font doesn't work too. Whole bourbon seems to not work. Only bitters works.

**Comment by tysongach** [comment]
@flipflap The font variables have changed, as well. `$helvetica` is now `$font-stack-helvetica`.

There will be a new documentation website when `5.0` is released. It’s a work-in-progress, but it might help you now: http://bourbon.netlify.com/docs/latest/

**Comment by flipflap** [comment]
Thank you. I see, it works... I didn't expect that, it seems 90% removed...

**Comment by tysongach** [comment]
> it seems 90% removed

I think we are at about 60% of features removed, between `4.2.7` and `5.0`. _Nearly all_ of those were just prefixing mixins, though. And most of those were simply an alias for our `prefixer` mixin. The reason is that better tools for this exist, like Autoprefixer. They let you drill down to specific browser support and write much less CSS/Sass, letting automation take over. You can read more about this here: https://github.com/thoughtbot/bourbon/issues/702.

**Comment by flipflap** [comment]
It makes sense, thank you!
