### ISSUE TITLE
Mixin transform error

### ISSUE THREAD

**Issue by Quentame** [thoughtbot/bourbon#984]
### Expected behavior
No errors on Sass compilation

### Actual behavior
Hello, I'm receiving an error during the Sass compilation:
ERROR: myFile (Line 315 of target/rubygems/gems/compass-core-1.0.3/stylesheets/compass/css3/_transform.scss: Mixin transform takes 1 argument but 2 were passed.)

### Steps to reproduce behavior
- Install Ruby
- Install Sass
- Install Bourbon
- Try [Simple CSS-only Loading Spinner](http://codepen.io/msisto/pen/LntJe?editors=1100#0) 

### Bourbon version
4.2.7

### Environment info
Ruby: 2.3.1
Sass: 3.4.22

**Comment by tysongach** [comment]
@Quentame Hello!

This appears to be an issue because you have Compass in your project, as seen in the path you provided above:

```
target/rubygems/gems/compass-core-1.0.3/stylesheets/compass/css3/_transform.scss
```

The CSS output on CodePen is as expected, with no compilation errors.

Compass _also_ has a mixin named `transform`, so my bet is that you are passing in two arguments—which is how the Bourbon mixin works—but Compass is imported after Bourbon, so the Compass mixin is being called, and it only accepts one argument.

I’d suggest a couple things:
- Remove Compass and stick to just one library/framework.
- Review browser support for `transform` via [Can I Use](http://caniuse.com/#feat=transforms2d) and see if you even need prefixes. Support is pretty strong these days, so you could use the spec now.

**Comment by Quentame** [comment]
Hi !
Yes I do have Compass imported but before.

Thanks for the answer, I will see what to do.
