### ISSUE TITLE
unprexfixed output from `display(flex !important)`

### ISSUE THREAD

**Issue by placenamehere** [thoughtbot/bourbon#992]
### Expected behavior

When passing `flex !important` through the `display` mixin, i would expect the output would be all the box & flex variations, including vendor prefixes, as `flex` outputs, with the addition of the `!important` rule.

### Actual behavior

Because the prefixing logic of `display` is fairly brute force, `flex !important` fails the first conditional and skips over to the else statement where it simply echos back the `$value` argument.

I realize the question `!important` support as a whole has mostly been asked an answered (including in #900), and you've moved onto 5.0, but this use case feels like some logic flaws.

### Steps to reproduce behavior

reproduce with `@include display(flex !important)` or `@include display(inline-flex !important)`

### Bourbon version

4.2.7

**Comment by placenamehere** [comment]
fixed this locally by monkey patching the display mixin and adding additional 2 additional else if blocks, checking for `inspect($value) == "flex !important"` etc. not really dry, but i can submit a PR if there isn't a more elegant way to write that in sass.

**Comment by tysongach** [comment]
Hi @placenamehere!

Thanks for doing your homework and referencing old issues/comments. I have mixed feelings on offering support for `!important` statements within Bourbon features. I’m not against them all-together, but there is a time and a place. [Harry has some nice thinking on this](https://csswizardry.com/2016/05/the-importance-of-important/).

Couple thoughts/thinking out loud:

- As you mentioned, the `display` mixin has been removed in v5.0.
- We are no longer adding new features to the 4.x release cycle. I’d definitely encourage moving away from Sass-based prefixing, if possible.
- I’m wary of adding support for `!important` statements on mixins because a lot of them output multiple properties and values, and I think it would add confusion as to _what_ gets the `!important` statement (all values that the mixin outputs, or just some?).
- I sort of like that you can’t use `!important` with Bourbon mixins because they should be used within a known system/framework/guideline and their usage needs to be super duper clear. They’re very powerful and can come with consequences. Leaving `!important` to vanilla CSS—rather than wrapped up within mixins or other Sass—reduces unknowns and confusion, and enforces clarity.

Thoughts?

**Comment by placenamehere** [comment]
Personally: I tend to side with the project's opinion that css architectures that would have one rely on the `!important` selector aren't a good practice - in no small part as they can create developer confusion and specificity arms races. I also think the v5.x move to offload any prefixing elsewhere is great for similar reasons (more consistent if using another tool in the pipeline for just that job)

But looking at bourbon as a consumer of it, I filed this issue not because as a tool I felt I got mixed and inconsistent results from mixing in the same file (`_flex-box.scss`). My current codebase relies a lot on the `prefixer` mixin - either directly or because it's called in other bourbon mixing, which, because it just passes through the `$value` we got expected results from both values with and without `!important` so we didn't use a post processor. The `display` mixin, without `!important` also outputs the prefixed values, so we can skip the prefixer call there. However, as stated above, the `display` mixin when the `$value` argument contained `!important` didn't result in anything prefixed.

Here's a straight forward example (note: i didn't actually write the 3rd line, it's just a good example of where the same bouborn code behaves differently)

`@include order(1)`
`@include order(1 !important)`
`@include display(flex)`
`@include display(flex !important)`

3 out of 4 of those calls worked one way, and the other didn't.

**Comment by placenamehere** [comment]
The other reason i field was for issue-as-documentation.

And with confirmation that dev on 4.x is dead it also makes me feel better about forking 4.7 and making this change for us without having to worry about maintaining that fork until we switch to 5.x.

So fee free to close. Satisfied with that outcome.

**Comment by tysongach** [comment]
Thanks for the detailed the response. This all makes sense. We never designed any of the features to support or not support `!important`, so results may vary (as it seems you have found).

I think for now, as a library, we’re choosing to not implement support for `!important`. But please feel free to fork; the 4.x cycle will no longer receive new feature development.

> The other reason i field was for issue-as-documentation.

And thank you for that!
