### ISSUE TITLE
Using triangle mixin with one size value in 5.0

### ISSUE THREAD

**Issue by Trost123** [thoughtbot/bourbon#994]
In version 4 I was creating two triangles, using:

```scss
@include triangle(9px, gray, down);
@include triangle(9px, white, right);
```

And it resulted in what you'd expect: right and down triangles of the same size.
http://prntscr.com/e1eo6z

In version 5 I changed the parameter order to fit new specs:

```scss
@include triangle(down, grey, 9px);
@include triangle(down, white, 9px);
```

http://prntscr.com/e1epai

The triangles with direction-right get squashed vertically now.

```scss
@include triangle(right, grey, 4px, 9px);
```

Manually imputing width and height fixes the triangle to look like in screenshot 1, but it looks like a downgrade from v4 behavior. If you input one value for a triangle - it should be it's biggest side (hypotenuse), no matter what orientation it is.
Same for diagonal ones: if I try to create down-right triangle, 9px size, I get way bigger triangle, than a down-oriented triangle 9px size.

**Comment by tysongach** [comment]
Hi @Trost123!

The aim by re-working the mixin was to make the argument values being set more clear and expected.

> If you input one value for a triangle - it should be it's biggest side (hypotenuse), no matter what orientation it is.

This is nicety when the mixin was called, however, I think it is an assumption that everyone would see the one value as always being the longest side.

With the new mixin, the width and height set will always map directly to the width and height of the "box" the triangle sits in. I like the clarity of that, because that is the actual space it takes up when rendered. In the old mixin, if you pass one value, you’d have to know that that value is either the width _or_ the height, depending on the value set for the direction. 

I’m now wondering if we should remove the default values from the arguments so that authors have to define values for the four arguments each time the mixin is called.

**Comment by Trost123** [comment]
I think 90% uses of triangle mixin are for [isosceles right triangle](http://mathworld.wolfram.com/IsoscelesRightTriangle.html) and not that [squashed grey thing](http://prnt.sc/e1epai) I got in a screenshot.
So, while I agree with "box" size concept you have in mind, why is box height = width/2 for left\right triangles right now?

I always imagined a html triangle as a 1\4 segment of a square pizza](http://prntscr.com/e1lqas).
And the images in old documentation worked for me as soon as I saw it.
That's why I never knew about the fourth parameter when using Bourbon v4.
Size = "bounding square" (not rectangle) side.

Here are variations I came up with for:
`triangle(10px, color, side);`
1) Bourbon 4 style:
left\right triangle = width: 5px, height: 10px;
up\down = width: 10px, height: 5px;
2) First parameter is always width, but height is calculated to keep 1:2 ratio the right way:
left\right triangle = width: 10px, height 20px;
up\down triangle = width: 10px, height: 5px;
3) Throw an error. Always ask for 4 parameters for consistency.

It's up for debate, but currently, 3 parameter triangles pointing right-left look horrible. Haven't tried diagonal ones yet.

**Comment by tysongach** [comment]
I think the path forward is to remove the defaults and always ask for 4 arguments. It’s the most consistent and clear implementation.

Just like we did the with `size` mixin, `$height` and `$width` should be individual arguments (`($height, $width)`) and not a a list (`($height $width)`). I don’t think we can accomplish that and allow for a single width value to be set, because something that would be the actual width, and other times it would equal the height. I find that confusing.

**Comment by tysongach** [comment]
https://github.com/thoughtbot/bourbon/commit/3a20e27709b9f4d1aa6a612ee0f30c56209efb21 changes the `triangle` mixin to no longer have default argument values.
