### ISSUE TITLE
[4.3.0] 'assign-inputs', 'strip-units' and 'em' used in global variables, emitting deprecation warnings

### ISSUE THREAD

**Issue by MightyPork** [thoughtbot/bourbon#997]
- `assign-inputs` used in `addons/_text-inputs.scss` and `addons/_buttons.scss` for global variables (which coincidentally are really useful)
- `strip-units` and `em` used in modular-scale's default base in `functions/_modular-scale.scss`

**Comment by DanHaddock** [comment]
I am seeing these WARNING appearing when I trigger the 'gulp' command to launch my website.

Would be great to find out why this might be happenning. :)

**Comment by AlennGK** [comment]
Yea, and if it is intentional I would like to disable these warnings =)

**Comment by MightyPork** [comment]
@AlennGK To disable them, we can use the following:

    $output-bourbon-deprecation-warnings: false;

But since 4.3.0 does nothing but add those warnings, I'll be using 4.2.7 until this issue is resolved.

**Comment by tysongach** [comment]
Hi all,

Yes, this is intentional. We released 4.3 which adds these deprecation warnings in preparation for the 5.0 release. Bourbon follows [Semantic Versioning](http://semver.org/) and 5.0 is a major release that has breaking changes. To help people prep for that and to follow standard open-source library conventions, these warnings to added to indicate what has been removed/changed in 5.0.

To explain the specific deprecations mentioned above:

- `assign-inputs` was not labeled as a private function previously and in 5.0 it was renamed (to `_assign-inputs`) to help indicate so. Going forward, we now have a system for public and private features to help prevent confusion.
- `strip-units` is renamed to `strip-unit` in 5.0.
- `em` is removed in 5.0.

I know it doesn’t always make sense to upgrade a Sass library to the next major version, so if you’d like to stop these warnings, you have two options:

1. Lock your version of Bourbon back down to 4.2.7. The deprecation warnings were the only thing added in 4.3, so you won’t be missing out on anything.
2. You can set a variable in 4.3 to tell Bourbon not to output the deprecation warnings: `$output-bourbon-deprecation-warnings: false;`

**Comment by MightyPork** [comment]
@tysongach 
The issue I tried to report is that the framework is itself still using those deprecated mixins, so even if you fix your application code, there'll still be deprecation warnings you can't get rid of.

I tried to clean the output of warnings, but eventually just stashed it and locked Bourbon to the older version...

**Comment by tysongach** [comment]
@MightyPork Correct. It’s a bummer, which is why we now have a system for public and private features. `assign-inputs` is only used internally to Bourbon to build other features, but since it was not labelled as a private function, some people used it directly within projects. So when it gets renamed in 5.0, we want to provide warnings for that.

`strip-units` and `em` are public-facing, documented features, so they also need deprecation warnings. But the `modular-scale` piggy-backed on those features in 4.x (in 5.0, it no longer does).

These are caused by poor library organization on our part and 5.0 takes huge leaps forward in bettering that.

If you’ve resolved all deprecation warnings in your application code and only see warnings from Bourbon’s own use, can you set `$output-bourbon-deprecation-warnings: false;`?

**Comment by tysongach** [comment]
We just released v4.3.1, which should prevent internal deprecation warnings from being thrown.

**Comment by ItcomsUAL** [comment]
In the current online documentation `strip-units` does not have any 'deprecated in v5' note, AFAICT. Is this an oversight?
